<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Enums\" />
    <Folder Include="Infrastructure\Data\" />
    <Folder Include="Infrastructure\FiscalSAR\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Radzen.Blazor" Version="11.5.1" />
  </ItemGroup>

</Project>
